# Generated by Django 3.2.23 on 2024-10-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientconsultation',
            name='dob',
        ),
    ]
