# Generated by Django 3.2.23 on 2024-10-30 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_patientconsultation_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='status',
            field=models.CharField(blank=True, default='NOT COMPLETED', max_length=100, null=True),
        ),
    ]
