# Generated by Django 3.2.25 on 2024-07-25 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_heading', models.CharField(max_length=200)),
                ('p_description', models.TextField()),
            ],
        ),
    ]
