# Generated by Django 3.2.23 on 2024-10-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_patientconsultation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientconsultation',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
