# Generated by Django 3.2.23 on 2024-09-27 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orpahan_care'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
            preserve_default=False,
        ),
    ]
