# Generated by Django 3.2.23 on 2024-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_doctors_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
