# Generated by Django 3.2.23 on 2024-11-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
