# Generated by Django 3.2.23 on 2024-11-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientconsultation',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
