# Generated by Django 3.2.23 on 2024-10-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_doctors_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.departments'),
        ),
    ]
