# Generated by Django 3.2.23 on 2024-11-27 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_doctors_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Image',
        ),
    ]
