# Generated by Django 3.2.23 on 2024-12-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
